name: ecommerce_application
description: "A new Flutter project."


publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


#------------------Packages---------------------#
dependencies:
  flutter:
    sdk: flutter
  # Utility Packages


  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.6

  # State Management
  get: ^4.7.2

  # Product Specific



#------------------ ./ Packages End---------------#
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0





flutter:
  uses-material-design: true

  #------------------- LOCAL ASSETS -----------------#

  assets:
    - assets/logos/
    - assets/images/
    - assets/icons/


  #------------------- LOCAL FONTS -----------------#

  fonts:
    - family: Poppins
      fonts:
         # - asset : assets\fonts\coolvetica rg it.ttf
         # - asset : assets\fonts\coolvetica rg.ttf
         - asset : assets\fonts\Poppins-Black.ttf
         - asset : assets\fonts\Poppins-BlackItalic.ttf
         - asset : assets\fonts\Poppins-Bold.ttf
           weight: 800
         - asset : assets\fonts\Poppins-BoldItalic.ttf
         - asset : assets\fonts\Poppins-ExtraBold.ttf
         - asset : assets\fonts\Poppins-ExtraBoldItalic.ttf
         - asset : assets\fonts\Poppins-ExtraLight.ttf
         - asset : assets\fonts\Poppins-ExtraLightItalic.ttf
         - asset : assets\fonts\Poppins-Italic.ttf
           style: italic
         - asset : assets\fonts\Poppins-Light.ttf
           weight: 300
         - asset : assets\fonts\Poppins-LightItalic.ttf
         - asset : assets\fonts\Poppins-Medium.ttf
           weight: 500
         - asset : assets\fonts\Poppins-MediumItalic.ttf
           weight: 500
           style: italic
         - asset : assets\fonts\Poppins-Regular.ttf
           weight: 400
         - asset : assets\fonts\Poppins-SemiBold.ttf
           weight: 600
         - asset : assets\fonts\Poppins-SemiBoldItalic.ttf  
